app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",HomeView.as_view(), name="home"),
    path("blog/", include("blog.urls", namespace="blog"))
    
]

app/blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name="blog"

urlpatterns = [
    path("", BlogListView.as_view(), name="home"),
    path("create/", BlogCreateView.as_view(), name="create"),
    path("<int:pk>/", BlogDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", BlogUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", BlogDeleteView.as_view(), name="delete")
]

app/blog/models.py
from turtle import title
from django.db import models

# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=250)
    content=models.TextField()

    def __str__(self):
        return self.title

app/blog/forms.py
from django import forms

from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title','content')

app/app/views.py
from django.views.generic import View 
from django.shortcuts import render 


class HomeView(View):
    def get(self, request, *args, **kwargs):
        context={

        }
        return render(request,"index.html",context)

app/blog/views.py
from audioop import reverse
from multiprocessing import context
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy


# Create your views here.
class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts=Post.objects.all()
        context={
            'posts':posts
        }
        return render(request,"lista2.html", context)

class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form=PostCreateForm()
        context={
            'form':form
        }
        return render(request, "crear.html", context)

    def post(self, request, *args, **kwargs):
        if request.method=="POST":
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get("title")
                content = form.cleaned_data.get("content")
                p, created = Post.objects.get_or_create(title=title, content=content)
                p.save()
                return redirect ('blog:create')

        context={

        }
        return render(request, "crear.html", context)

class BlogDetailView(View):
    def get(self,request, pk, *args,**kwargs):
        post = get_object_or_404(Post,pk=pk)
        context={
            'post':post
            }
        return render (request,"detail.html", context)

class BlogUpdateView(UpdateView):
   model=Post
   fields=['title','content']
   template_name='update.html'

   def get_success_url(self):
        pk=self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})

class BlogDeleteView(DeleteView):
    model=Post
    template_name='delete.html'
    success_url=reverse_lazy('blog:home')

app/templates/crear.html
{% extends 'index.html' %}

<div class="container" id="fondo">
    {% block content %}
    <form method="POST">
        {% csrf_token %}
        title:{{form.title}}
        <br>
        <br>
        content:{{form.content}}
        <br>
        <br>
        <button tipe="submit">crear post</button>
    </form>
</div>
{% endblock %}

app/templates/delete.html
{% extends 'index.html' %}

<div class="container">
    {% block content %}
        <form method="POST">
        {% csrf_token %}
        <p>Esta accion es irreversible, seguro que quieres borrar el post: {{post.title}}</p>
        <br>
        {{form}}
        <button tipe="submit">Borrar post</button>
        </form>
    {% endblock content %}
</div>

app/templates/detail.html
{% extends 'index.html' %}

<div class="container">
    {% block content %}
        <br>
        <h3>{{post.title}}</h3>
        <br>
        <p>{{post.content}}</p>
        <br>
        <a href="{% url 'blog:create' %}">crea un nuevo post dando click aqui</a>
        <br>
        <a href="{% url 'blog:home' %}">volver a posts</a>
    {% endblock %}
</div>

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <title>{% block title %}pureba de documento{% endblock %}</title>
    </head>

    <body>
        <nav>
            {% block navbar %}
                <div>
                    <ul class="nav navbar-nav">
                    <li><a href="#">Contacto</a></li>
                    <li><a href="{% url 'blog:home' %}">Blog</a></li>
                    <li><a href="#">Inicio</a></li> 
                    </ul>
                </div>
            {% endblock %}
        </nav>
        <div class="container">
        {% block content %}

        {% endblock %}
        </div>
        <br>
        <footer>
            <p> Gracias por visitarnos!! </p>
        </footer>
    </body>
</html>

app/templates/lista2.html
{% extends 'index.html' %}

<div class="container" id="fondo">
    {% block content %}
        <h3>Posts publicados</h3>
        <ul>
        {% for post in posts %}
            <li><a href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
            <a href="{% url 'blog:update' post.id %}">actualizar</button>
            <a href="{% url 'blog:delete' post.id %}">borrar</a>
            </li>
        {%endfor%}
        </ul>
        <br>
        <br>
        <a href="{% url 'blog:create' %}">volver a crear posts</a>
    {% endblock %}
</div>

app/templates/update.html
{% extends 'index.html' %}

<div class="container">
    {% block content %}
        <form method="POST">
        <h3>vista para actualizar post</h3>
        {% csrf_token %}
        title:{{form.title}}
        <br>
        <br>
        content:{{form.content}}
        <br>
        <br>
        <button tipe="submit">save post</button>
        </form>
    {% endblock  %}
</div>